### ISSUE TITLE
Delete "go_multi_language" branch?

### ISSUE THREAD

**Issue by DarwinNE** [DarwinNE/FidoCadJ#114]
Hi @MigthyThor 
should we delete the "go_multi_language" branch of the project?

If I recall correctly, the code tested in that branch has been integrated completely into the "gh-pages" branch so there is no need to keep "go_multi_language", isn't?

Kind regards,

D.

**Comment by MigthyThor** [comment]
yep!

**Comment by DarwinNE** [comment]
Thanks, I'll do that.

Kind regards,
D.

**Comment by DarwinNE** [comment]
Done! Thanks @MigthyThor
