### ISSUE TITLE
"Export complete" message box is too disruptive

### ISSUE THREAD

**Issue by Max2433BO** [DarwinNE/FidoCadJ#117]
Hi,

This isn't a problem but a feature request for new release of FidoCadj.

Synthetically the request is as follows:

1) I do a drawing
2) I save it and I export it (for example as EPS format)
3) I open the same file to correct it, then I save it
4) I export it with the same name (as in step 2)
5) Appears a window that ask if I want to overwrite (I click OK)
6) then a window appears that indicates to me that the file was saved...

... **but this last window will remain until you press OK**

Considering that it represents only a warning, not an alarm message, it could not do so after a few seconds closes without having to click on ok?

Bye, Max

Window in question in the Italian version
![schermata_esportazione_riuscita](https://cloud.githubusercontent.com/assets/16986987/18389276/916acd46-76a5-11e6-981f-ef61a6988507.png)

**Comment by DarwinNE** [comment]
Hi @Max2433BO 
I agree, this dialog box is definitely quite annoying!

**Comment by DarwinNE** [comment]
Hi @Max2433BO 
I think a notify in the coordinate region would do the trick.
It may be erased by the coordinates if the mouse is moved. Much less disruptive than the modal dialog you shown.


![notify](https://cloud.githubusercontent.com/assets/11355790/19017119/89ea05b4-882f-11e6-9ce2-9467c733fb20.png)


Cheers,
D.

**Comment by Max2433BO** [comment]
Hi, @DarwinNE

It might be an idea, but do not be too out of sight with respect to the "export" dialog box?

After clicking on "OK" closes the window and not seeing anything special happen (the writing is, as mentioned, out of sight) I wonder: The file will be exported?

... But maybe I worry too much!

Bye, Max

**Comment by DarwinNE** [comment]
Hi @Max2433BO 
  I do not like very much having a timeout in a modal dialog frame.
Maybe I can change of the message colour (green?) for a while.

Cheers,
D.

**Comment by Max2433BO** [comment]
> _Maybe I can change of the message colour (green?) for a while._

Why not... ;)

Bye, Max

**Comment by DarwinNE** [comment]
Hi,
  here is what I obtained:

![enough](https://cloud.githubusercontent.com/assets/11355790/19020859/78320e5e-88b4-11e6-8563-10b99d91f028.png)

That should be visible enough, in my opinion.
The colours became normal when the mouse is moved and the coordinates shown.

Cheers,

D.

**Comment by Max2433BO** [comment]
Perfect!!! You're a big, @DarwinNE  :)

Bye, Max

**Comment by DarwinNE** [comment]
Thanks @Max2433BO 

I renamed this issue for future reference, I am closing it now.

Cheers and thanks,
D.
