### ISSUE TITLE
Hide the search area and Libraries

### ISSUE THREAD

**Issue by Max2433BO** [DarwinNE/FidoCadJ#127]
Hi, @DarwinNE 

Even this is a request from a Electroyou forum user:

> It would be possible to hide the right of the main window of fidocaj (for instance the one that contains the search area and the tree of the libraries)?

> This would maximize the working area if using for the freehand drawing.

Bye, Max

**Comment by DarwinNE** [comment]
Seems a good idea. It remains to see if the interface is not becoming confusing for an inexperienced user, but let us try.

Addressed in commit 4c0d388
