### ISSUE TITLE
Change the color values in more direct way

### ISSUE THREAD

**Issue by Max2433BO** [DarwinNE/FidoCadJ#128]
Hi, @DarwinNE 

I propose just another request from a Electroyou forum user:

Currently if you want to change a color among those defined for layers, you must follow this procedure (from FidoCadJ italian version):

1) Select **Vista** menu
2) Select **Layer**
... or, if one remembers, press **Ctrl+L**
3) It opens the **Layer editor** window
4) In the **Layer editor** window, select the color to change
5) Select **Modifica**
6) Opens, finally, the **Opzioni del layer** window

... four clicks to reach the Color Editor !!

It would be possible to insert the entry **Opzioni del layer** directly in the menu that appears when you click on the right mouse button on a selected object?
And you couldn't make sure that the changes are immediately visible on the drawing prior to confirmation?

Thanks, Max

**Comment by DarwinNE** [comment]
Can be this considered similar to issue #24?
