### ISSUE TITLE
Proposal: Extend the limit of 250 points in drawing curves

### ISSUE THREAD

**Issue by Max2433BO** [DarwinNE/FidoCadJ#129]
Hi, @DarwinNE 

A mutual friend, Electroyou forum user, asks if it's possible to extend the limit of 250 points in the tracing of open curves or closed curves.

This is because, by using another program that translates images from jpeg files in .fcd, if that generates a curve with more than 250 points this is no longer visible.

Bye, Max

**Comment by DarwinNE** [comment]
Addressed in commit 93bf194

**Comment by DarwinNE** [comment]
Fully addressed in commit 4f3f3b8  

The limit is now 10000 tokens in a line, which means that a curve can contain almost 5000 points.
