### ISSUE TITLE
Fidocadj 0.24.7. alpha: "Holes" in display tree libraries

### ISSUE THREAD

**Issue by Max2433BO** [DarwinNE/FidoCadJ#131]
Hi, @DarwinNE 

In 0.24.7.alpha version of Fidocadj we found a tree problem viewing of libraries: 

if you open the list of "Componenti discreti - Libreria standard" (Italian version) you will notice a "hole" on top of "Resistenza" and above "Resistenza variabile", but if you look inside the "Libreria standard - Componenti discreti", actually there are two types of "Resistenza" and "Resistenza variabile" (Note that the same open list with 0.24.6 FidoCadJ version does not have the same problem).

**Image 0.24.7 alpha version**
![componenti_discreti_fidocadj_0_24_7_alpha](https://cloud.githubusercontent.com/assets/16986987/22175203/cc0aaffc-dff0-11e6-94e9-c182d5e350e6.png)

**Image 0.24.6 version**
![componenti_discreti_fidocadj_0_24_6](https://cloud.githubusercontent.com/assets/16986987/22175208/d2ea6e20-dff0-11e6-9d70-3ed2666a6e60.png)

Also this defect is present only in that section of the "Libreria standard" and in no other embedded library in the .jar file of the Fidocadj 0.24.7 alpha version.

Bye, Max

**Comment by Max2433BO** [comment]
Hi, @DarwinNE 

I got an idea: it isn't that the fidocadj 0.24.7 alpha version not accept two identical names of components in the same library section?

Out of curiosity I tried to change the name of each of the "Resistenza" and "Resistenza variabile" duplication (I added a B down)...

... and, as you can see, actually, so the "holes" problem disappears.


![componenti_discreti_modificati_fidocadj_0_24_7_alpha](https://cloud.githubusercontent.com/assets/16986987/22180731/f85b038a-e078-11e6-9f74-4b7c2f4f0871.png)


Bye, Max

**Comment by DarwinNE** [comment]
Hello,
  thanks, I could replicate the issue. Now I just have to try to understand why it happens :-)

D.

**Comment by DarwinNE** [comment]
I think I solved the problem. Thanks @Max2433BO your suggestion was correct, it was related to the name of the component. That greatly helped me and the solution was then easy to find!
Thumbs up!

I am closing this for the moment.
d.
