### ISSUE TITLE
Realign on grid

### ISSUE THREAD

**Issue by PietroBaima** [DarwinNE/FidoCadJ#138]
Following an interesting matter under discussion on ElectroYou [(here)](http://www.electroyou.it/forum/viewtopic.php?f=1&t=70141&p=722430#p722357) regarding a schematic which was not aligned with the grid, I wonder whether it would be possible to add a button for it.

I have no idea about the effort required, so in case the idea is not feasible because of overcomplication... no worries at all. :)

Many thanks
Pietro

**Comment by DarwinNE** [comment]
I do not know if this is feasible or not, but it may be worth to try.

**Comment by DarwinNE** [comment]
I thought about it and I think it is probably something very difficult to implement in a clean and universal way.
