### ISSUE TITLE
Incorrect export of dashed lines

### ISSUE THREAD

**Issue by Max2433BO** [DarwinNE/FidoCadJ#142]
Hi @DarwinNE ,
I report a little bug (... I hope ;) ):

if I export a dotted line in .png or .jpg format, I get a continuous line (or a very dense dotted line), but if I export in .pdf format the dotted line are right.

For example, with this file:

> [FIDOCAD]
> FJC C 3.0
> FJC A 0.8
> FJC B 0.8
> LI 30 20 120 20 0
> LI 30 25 120 25 0
> FCJ 0 0 3 2 1 0
> LI 30 30 120 30 0
> FCJ 0 0 3 2 2 0
> LI 30 35 120 35 0
> FCJ 0 0 3 2 3 0
> LI 30 40 120 40 0
> FCJ 0 0 3 2 4 0

you get these images

![prova_tratteggio](https://user-images.githubusercontent.com/16986987/35778927-99bd7b60-09c5-11e8-873b-b5098e8d0aa2.jpg)
.jpg image export

![prova_tratteggio](https://user-images.githubusercontent.com/16986987/35778931-a06804c6-09c5-11e8-8586-0243d4eabbfb.png)
.png image export

[Prova_tratteggio.pdf](https://github.com/DarwinNE/FidoCadJ/files/1692928/Prova_tratteggio.pdf)

I work with FidoCadj 0.24.7 on Ubuntu 16.04 64 bit, with openjdk version 1.8.0_151 

That's all!!

Max

**Comment by DarwinNE** [comment]
Indeed, there was a bug. Should be fixed now.
