### ISSUE TITLE
Buttons are displayed badly with Oracle Java / OpenJDK higher than version 8

### ISSUE THREAD

**Issue by alan-ford** [DarwinNE/FidoCadJ#149]
I use FidoCadJ on Ubuntu and I noticed that the buttons are displayed badly with Oracle Java / OpenJDK higher than version 8.

![fcj-problem](https://user-images.githubusercontent.com/44990009/48387897-cc146780-e6f7-11e8-9105-37e29d38731f.png)

**Comment by DarwinNE** [comment]
Thanks @alan-ford 
I see two things:
- text is not complete
- the UTF-8 char in Bézier is not displayed correctly

Is the UTF-8 problem only visible with OpenJDK >8? Is the same with other versions? Is the same with Oracle's JDK?

D.

**Comment by alan-ford** [comment]
Yes, the same problem also with Oracle> 8

**Comment by DarwinNE** [comment]
I upgraded to JDK 14.0.1 and I could reproduce the issue, particularly evident with the French language.
![pb](https://user-images.githubusercontent.com/11355790/80288580-1a28f980-8739-11ea-8a28-834561804693.png)
