### ISSUE TITLE
Ver. 0.24.7: Inverted filter symbols

### ISSUE THREAD

**Issue by alan-ford** [DarwinNE/FidoCadJ#153]
The high pass and low pass filter symbols are reversed.
![filter](https://user-images.githubusercontent.com/44990009/56691793-135c4680-66e1-11e9-863d-2241d785c896.png)

**Comment by DarwinNE** [comment]
Hi and thanks for the suggestion.
I'll swap the descriptions soon.

**Comment by DarwinNE** [comment]
I changed descriptions for the two symbols. That should fix the problem.
