### ISSUE TITLE
Problem with dashed curves

### ISSUE THREAD

**Issue by Max2433BO** [DarwinNE/FidoCadJ#161]
Hi, @DarwinNE 

I report the following problem regarding the use of dashed curves.

Consider the following FidoCadJ source:
```
[FIDOCAD]
FJC C 3.0
FJC A 0.8
FJC B 0.5
LI 156 179 218 134 0
FCJ 2 0 3 2 1 0
BE 52 252 65 304 111 224 61 235 0
FCJ 2 0 3 2 1 0
CV 0 96 66 121 71 121 81 91 81 74 81 73 66 91 66 2
FCJ 2 0 3 2 1 0
```
This generates a line, a curve and a bézier all dashed.

If I export these figures in the formats provided by FidoCadJ, only the .png and .jpg formats allow me to see the dashed curve, the others show it to me continues (the line and the bézier, instead they continue to remain dashed)

Note: I can't test the .pcb, .pgf and .scr formats.

However, in the .png and .jpg formats, if I use a resolution greater than 300x300, all the figures appear to me continuous.

If, in FidoCadJ, I press CTRL + G to see the source of the image and I close the related window, only the dashed curve becomes continuous.

If I copy these figures (CTRL + A followed by CTRL + C), I open a new FidoCadJ window and paste the whole (CTRL + V), only the dashed curve appears as continuous.

Note: in these latter cases, if you look at the image source (CTRL + G) you notice that the FCJ command relating to the curve loses the dash flag (Example: with dashes FCJ 2 0 3 2 1 0, without dashes FCJ 2 0 3 2 0).

Furthermore, if I save the image (source in .fcd format), even there the dash flag for the curve disappears.

All tests were performed with version 0.24.7

If I repeat the tests with version 0.24.8_alpha the only improvement you get is the ability to export in .png and .jpg formats with resolutions up to 2400x2400 dpi without losing any dashes.

If I repeat the test with version 0.24.6 the only improvement is obtained by copying the image to another window: in this case the curve appears dashed.

I apologize if in some places I am not very clear but, given my poor knowledge of English, I often have to rely on automatic translators ...

That's all.

Bye, Max.

**Comment by DarwinNE** [comment]
This issue should have been corrected.
