### ISSUE TITLE
New version of library lib_agg

### ISSUE THREAD

**Issue by Luigi-C** [DarwinNE/FidoCadJ#163]
Find attached a new version of my library lib_agg.
Even more symbols have been added.
[lib_agg.zip](https://github.com/DarwinNE/FidoCadJ/files/3585252/lib_agg.zip)

**Comment by DarwinNE** [comment]
Thanks! I will add it next week to the website. Can we say it is version 2.0?

**Comment by Luigi-C** [comment]
Yes, sure.

**Comment by DarwinNE** [comment]
Better leave this open... I will surely forget to update the website if we close it now :-)

**Comment by DarwinNE** [comment]
The file is updated on the website.
