### ISSUE TITLE
Add Norator and Nullator at EY_Libraries.fcl

### ISSUE THREAD

**Issue by Max2433BO** [DarwinNE/FidoCadJ#167]
Hi @DarwinNE ,

I added these two components to EY_Libraries.fcl at the request of an Electroyou forum member.

If you want you can add it to the next version of FidoCadJ.

Bye, Max

Note: To load it I had to change the extension file from .fcl to .txt

[EY_Libraries.txt](https://github.com/DarwinNE/FidoCadJ/files/4023605/EY_Libraries.txt)

**Comment by DarwinNE** [comment]
That is very interesting. Would it be possible to open a pull request?

**Comment by DarwinNE** [comment]
Thanks for the PR! I trimmed a little the symbols so that the terminals are aligned with the standard grid in commit 801045d6a4d5d58d37c36210ec8aded90f43463a
