### ISSUE TITLE
highlight the point of coordinates 100x100

### ISSUE THREAD

**Issue by Max2433BO** [DarwinNE/FidoCadJ#168]
Hi @DarwinNE ,

I have a question for you:

Is it possible to highlight the point on the 100x100 coordinate grid (with a cross or with a different color), since it is the center for the creation of new components?

Thanks!

Max

**Comment by DarwinNE** [comment]
Hello,
  when you define a new symbol in the library, you can put the origin (i.e. the point that becomes (100, 100) in the symbol definition) where you want:

![origine](https://user-images.githubusercontent.com/11355790/71812023-6ced8100-3076-11ea-9c44-ed021e27352a.png)

There is no need to highlight the (100,100) coordinate in FidoCadJ.

Cheers,
D.

**Comment by Max2433BO** [comment]
My mistake, sorry!!! o.O

I edited a library file directly, referring to chapter 3.6 of the Italian FidoCadJ manual, where reference was made explicitly to the 100x100 coordinates ...

 Max

**Comment by DarwinNE** [comment]
I think the manual is outdated. I had some trouble keeping the doc up-to date and I decided to concentrate myself only on the english documents.
