### ISSUE TITLE
A little issue of a component

### ISSUE THREAD

**Issue by iGreybear** [DarwinNE/FidoCadJ#173]
Hi DarwinNE,

in the following component "Simboli Elettrotecnica -> Contatti a due o tre vie -> Commut. bipolare due vie tre pos. centr. di apertura", two pins do not reach the point of grid.

Thanks for your help,
Domenico

**Comment by DarwinNE** [comment]
I found those symbols, where the bottom contacts are misaligned with respect to the default 5-unit grid:

![misaligned_symbols](https://user-images.githubusercontent.com/11355790/79741034-db421080-8300-11ea-8879-5b690df7c68f.png)

I will slightly shorten those. That will yield a minor incompatibility with previous versions of FidoCadJ, but it is worth to correct this.

**Comment by DarwinNE** [comment]
My last commit should correct those components. Don't hesitate to comment if you find similar bugs.
