### ISSUE TITLE
No paste command in text window

### ISSUE THREAD

**Issue by Max2433BO** [DarwinNE/FidoCadJ#174]
Hi @DarwinNE 

I found this problem in FidoCadJ 0.24.7 on linux s.o (Ubuntu 18.04.4) with jre 1.8.0_131:

if select a text in a window and copy with a right mouse button click then try to paste into the FidoCadJ text window, the paste command does not work (the relative window does not open).

See the attached example video (unzip the file):

[Video.zip](https://github.com/DarwinNE/FidoCadJ/files/4504531/Video.zip)

Bye, Max

**Comment by DarwinNE** [comment]
Hi @Max2433BO 
   I tried with a shortcut on MacOS (Command+V) and it works.
Is does the same on Linux (Control+V)?

Kind regards,
D.

**Comment by Max2433BO** [comment]
Yes, with ctrl+V it works, but using the menù with the right mouse button no (the menù does not appear)...

Max

**Comment by DarwinNE** [comment]
A contextual menu will not be implemented. Keyboard shortcuts will be enough there.
