### ISSUE TITLE
Copy / paste key command blocked

### ISSUE THREAD

**Issue by Max2433BO** [DarwinNE/FidoCadJ#182]
Hi @DarwinNE ,

I found a problem with the commands CTRL + C,  CTRL + V in FidoCadJ 0.24.7 and 0.24.8_delta.

If you try to use the commands mentioned above with focused zoom, they don't work: you can select the image with the mouse but by pressing the CTRL + C and CTRL + V keys nothing is obtained (the image remains highlighted in green).

Note: some times digits appear in the zoom box when the CTRL + V keys are pressed (see image)

![Blocco_copia_incolla](https://user-images.githubusercontent.com/16986987/80713806-57540980-8af4-11ea-80d7-d8070c9bdaa1.png)

If you deselect the zoom (for example by clicking in an empty part of the work window) the CTRL + C and CTRL + V sequence works normally.

Bye, Max

**Comment by DarwinNE** [comment]
The issue is that the zoom combo box element receives the focus way too often.
I'll try to fix this.
