### ISSUE TITLE
Grid: dot style vs line style

### ISSUE THREAD

**Issue by Max2433BO** [DarwinNE/FidoCadJ#188]
Hi @DarwinNE 

Since you are in the mood for change I propose an idea:

can you insert, in the options menu, the possibility of choosing whether to display the grid in points or in lines (like a Cartesian plane)?

In order not to disturb too much, the color of the lines could be, for example, the one called "other 9" (in the Italian version).

I propose this modification because I find it easier for the alignment of texts and components.

Let me know what you think.

Bye, Max

**Comment by DarwinNE** [comment]
I think the program can show the grid with points when the zoom is relatively small or with lines when the zoom is very large.
