### ISSUE TITLE
Parameter fields not the same options

### ISSUE THREAD

**Issue by JoopN** [DarwinNE/FidoCadJ#216]
I had a crazy idea, draw furniture and a room, then find the best possible setup. That's done successfully, but during that process I did  find strange difference which are not logic for me. See the enclosed picture. 
![All parameterfields combined](https://user-images.githubusercontent.com/8764153/174872347-b2025dc7-a8b0-4dd5-b50c-8548408beb18.jpg)

On top left  you find what's  available when you use the "Text tool" from the toolbar. When you did draw something with the "Line tool" or  the Rectangle tool" as an example and you choose for parameters you see the top right picture. And sometimes  its even down to just what can be seen in the left down picture, only name and value. Down right in the example you find the result from one of my drawings. Why are not every text parameters everywhere the same?

**Comment by DarwinNE** [comment]
The Parameters dialog differs depending on the element you want to customize. You do not have the same characteristics for a polygon, a PCB line or an electric connection.

That being said, in FidoCadJ, you have two types of text elements:
- text associated to another drawing element (Name and Value)
- text present as stand alone

In the first case (top right picture), you have a window that prompts you all the characteristics of the drawing element (I think it is a line in your example), therefore you see things about arrow heads, etc. The font and the size are the same for all text drawn this way in the drawing and can be set in the program preferences. The bottom picture is the exact same situation, referred to a macro.

In the second case (top left picture), you have a complete control on the text element and you can have multiple sizes and fonts in the drawing.

By the way, if you right-click on a drawing element having an associated text and select "split into elements", you separate the text tags that become stand-alone.

Hope it is clear!

**Comment by JoopN** [comment]
Sorry not clear enough. I know that one does a line and another does do something different. That's the tool. But almost all tools also can have text and only in one you can size it with x and y. With normal sized drawing not a real problem, but with this sized drawing I'm on 25% for 80% of the drawing. All text which could be sized are set bigger, but all text without those options are tiny, sometimes the size of the line. This difference can be seen in the right down picture. So if you can set  text, why not set the font and the size of it?

**Comment by DarwinNE** [comment]
Because it makes sense in a schematic that all the text associated to a drawing element (or a macro, for a component) has exactly the same characteristics.
If you need more control, just separate the text from the element and treat it as a normal stand alone element.

**Comment by JoopN** [comment]
Yes, that's what I do, leave parameters empty and set text with the text tool. For the rest of it, I think I don't fit into "standard" ;-)
