### ISSUE TITLE
English manual  table 3.3

### ISSUE THREAD

**Issue by JoopN** [DarwinNE/FidoCadJ#217]
I wonder why there is no option for italic text? May be its there, but omitted in the manual by mistake?
![3_3 Drawing elements table](https://user-images.githubusercontent.com/8764153/174876237-2e623a96-20f7-4813-9684-9c4c1b6722f0.jpg)

**Comment by DarwinNE** [comment]
I just forgot to indicate that bit 1 (weight 2) stands for italic.
I update the manual immediately.

**Comment by DarwinNE** [comment]
Done in commit beae81e895301073e0c6a11eba2b40b8fdef8a7b

**Comment by JoopN** [comment]
Okay, thank you.
