### ISSUE TITLE
Symbol definition dialog

### ISSUE THREAD

**Issue by JoopN** [DarwinNE/FidoCadJ#228]
Enclosed  a picture with translated text. The room behind the checkbox "snap origin on grid" is too short for some other languages. The translation is correct, but  there is not enough room for the text. Seems to me an easy fix.

![new_symbols_nl](https://github.com/DarwinNE/FidoCadJ/assets/8764153/8eebae6d-c967-41a5-8bdb-9eba5c12ee78)

**Comment by DarwinNE** [comment]
I see. I'll have a look at this soon.

**Comment by DarwinNE** [comment]
@manufino has worked on this issue. Can we close it, or there are other changes to be done?

**Comment by manufino** [comment]
I think we can close this. This should have resolved the issue.

![sym](https://github.com/user-attachments/assets/9453d121-531c-476d-87a7-c307f16cd2c1)

**Comment by JoopN** [comment]
Op Wed, 14 Aug 2024 12:37:22 -0700
Davide Bucci ***@***.***> schreef:

> @JoopN, did the last changes improve the issue?
> 

Sorry, did not know that there was a new version. Have to download
and see.

Regards,
Joop

**Comment by manufino** [comment]
> Op Wed, 14 Aug 2024 12:37:22 -0700 Davide Bucci ***@***.***> schreef:
> @JoopN, did the last changes improve the issue?
> Sorry, did not know that there was a new version. Have to download and see. Regards, Joop

I think you need to download the source code and compile it.

**Comment by manufino** [comment]
@DarwinNE, You can close this one for me as well.
