### ISSUE TITLE
README: broken link

### ISSUE THREAD

**Issue by Stemby** [DarwinNE/FidoCadJ#58]
http://www.cs.usask.ca/documents/techreports/2013/TR-2013-01.pdf

Is there a new working link?

Thank you!

**Comment by DarwinNE** [comment]
Hi,
  that is the problem with links...
I tried a research with FidoCadJ on Google Scholar. Among the alternative results, this one seems to work (but for how much nobody knows...)

http://ftp.cs.usask.ca/documents/techreports/2013/TR-2013-01.pdf

Or maybe this one:

https://www.cs.usask.ca/documents/technical-reports/2013/TR-2013-01.pdf

which seems to have a more modern url.

Cheers,
D.
