### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by Stemby** [DarwinNE/FidoCadJ#64]
This issue is similar to #51.

I think line breaks (newlines) should follow the Unix standard: only the Line Feed (LF) character, instead of the combination of Carriage Return (CR) + LF used by some limited OSes.

The only exception might be `winbuild.bat` (to be verified).

Fixing this issue is very simple (see the dos2unix command line software) but, as in #51, probably it would be a good idea to add a test for consistency.

**Comment by DarwinNE** [comment]
I completely agree. The Unix standard for line feed is the way to go.

**Comment by DarwinNE** [comment]
Added a Checkstyle rule and normalized the newlines for the sources.
