### ISSUE TITLE
"Libraries" page on the website is not mobile-friendly

### ISSUE THREAD

**Issue by DarwinNE** [DarwinNE/FidoCadJ#65]
The Libraries page on the website:

http://darwinne.github.io/FidoCadJ/libs.html

Is not currently considered as "mobile friendly" by the Google checker:

https://www.google.com/webmasters/tools/mobile-friendly/?hl=fr&url=http%3A%2F%2Fdarwinne.github.io%2FFidoCadJ%2Flibs.html

This may impact the search ranking.

**Comment by DarwinNE** [comment]
Is this issue still relevant with the new version of the website, @gremirarunico?
Can I close it?

**Comment by gremirarunico** [comment]
Yes, it can be closed.

**Comment by DarwinNE** [comment]
Ok.
