### ISSUE TITLE
"FAQ" page on the website is not mobile-friendly 

### ISSUE THREAD

**Issue by DarwinNE** [DarwinNE/FidoCadJ#66]
The FAQ page on the website:

http://darwinne.github.io/FidoCadJ/faq.html

Is not currently considered as "mobile friendly" by the Google validator:

https://www.google.com/webmasters/tools/mobile-friendly/?hl=fr&url=http%3A%2F%2Fdarwinne.github.io%2FFidoCadJ%2Ffaq.html

This may impact the ranking of the page.

**Comment by DarwinNE** [comment]
Is this issue still relevant with the new version of the website, @gremirarunico?
Can I close it?

**Comment by gremirarunico** [comment]
Yes, it can be closed!

**Comment by DarwinNE** [comment]
Ok?
