### ISSUE TITLE
"Abandoned" code

### ISSUE THREAD

**Issue by Stemby** [DarwinNE/FidoCadJ#68]
Please, could you put "abandoned" code (like `jar/Manifest_applet.txt` and `jar/*.html`) in a dedicated directory?

After that, I think README.md should be updated:
```
| `jar/`               |  X  | Contains `fidocadj.jar` as well as Quaqua       |
```
↓
```
| `jar/`               |  X  | Directory where to put JAR and manifest files   |
```
or similar.

Thank you very much!

**Comment by DarwinNE** [comment]
I agree. I also got rid of the test/tmpdir directory, which contained some old java code. I probably used that for a test two or three years ago, but it is not useful anymore.
I will reopen this issue if needed.
