### ISSUE TITLE
Missing screenshot in the website

### ISSUE THREAD

**Issue by DarwinNE** [DarwinNE/FidoCadJ#69]
Hi to all,
  if I click on the screenshot on the main page of the FidoCadJ project,

http://darwinne.github.io/FidoCadJ/

I obtain a 404 error, the link is not correct:

http://darwinne.github.io/FidoCadJ/images/creenshots/ecg.png

should be corrected in:

http://darwinne.github.io/FidoCadJ/images/screenshots/ecg.png

Cheers

**Comment by MigthyThor** [comment]
My bad! Sorry, fixed now!

**Comment by DarwinNE** [comment]
Thank you very much, MigthyThor! I merged your PR.
