### ISSUE TITLE
lines and geometric figures not visible

### ISSUE THREAD

**Issue by Max2433BO** [DarwinNE/FidoCadJ#76]
Hi, DarwinNE

if you try these code's lines

[FIDOCAD]
FJC B 0.5
LI 30 25 110 25 0
BE 30 35 110 35 110 35 110 35 0
CV 0 30 40 110 40 0
EV 30 50 110 50 0
RV 30 65 110 65 0

you see only two lines: the first and the last, but bezier line (BE), curve line (CV) and ellipse (EV) are hidden.

This problem appears if line's end point has the same Y-axis (or X-axis) of the origin.

In addition, the tracking of bezier, curve and ellipse, when the extremes are on the same Y-axis (or X-axis), the green track guide disappears from the screen so you have no idea where it was positioning the start point: the track appears if you move one step up the grid.

Bye, Max

P.S.

... Sorry for my bad english!!! :P

**Comment by DarwinNE** [comment]
Hi @Max2433BO,
  thanks so much for the bug report: I think I could fix it for the next version.
