### ISSUE TITLE
Reversed arrow with negative "arrow length"

### ISSUE THREAD

**Issue by Max2433BO** [DarwinNE/FidoCadJ#78]
Hi, DarwinNE

I read english manual (version 8/19/2015), at the 2.7 "Arrow and stroke styles" but I have not found any trace of this feature:

In a bezier (or normal) curve, if you set on "display arrow" (at the start or at the end), and you set "length tip" with a negative number, the arrow is show reversed.

![arrow](https://cloud.githubusercontent.com/assets/16986987/12786339/ea7949f6-ca90-11e5-845c-b74045494ae4.png)

However, with the line this "function" does not work.

This is the code only for curves:

[FIDOCAD]
FJC B 0.5
CV 0 15 5 40 35 55 20 0
FCJ 2 0 3 2 0 0
BE 85 20 115 35 130 15 150 30 0
FCJ 2 0 3 2 0 0
CV 0 15 45 40 75 55 60 0
FCJ 2 0 -3 2 0 0
BE 85 65 115 80 130 60 150 75 0
FCJ 2 0 -3 2 0 0

Bye, Max

**Comment by DarwinNE** [comment]
Hi @Max2433BO 
  at the beginning, I thought it was a bug, but then I realized that it may be interesting to document this behavior and make sort that it happens the same thing with the lines.

Cheers,
D.

**Comment by Max2433BO** [comment]
Good idea!!!

Bye, Max

**Comment by DarwinNE** [comment]
Everything should have been taken into account and updated. Negative length for arrows is now accepted and documented.
