### ISSUE TITLE
Missing 1° caracter on Zoom field

### ISSUE THREAD

**Issue by Cipollino** [DarwinNE/FidoCadJ#88]
Dear DarwinNE, in the zoom field (in the left up side) the first character of indication of zoom is missing if the zoom is higher to 999% (the 1000% is visualized 000% - the 1300% is visualized 300%, etc.)

Dear DarwinNE is only an problem of the alignement to right of the text and, if is possible, enlarge the field of zoom indicator for avoid same problem with different screen resolution monitor.

Many thanks.

**Comment by Cipollino** [comment]
Excuse me, I not indicated my version of FidoCADJ:   is  v0.24.6 delta.

**Comment by DarwinNE** [comment]
Hi,
  I increased the size of the box by 20% It remains to see if that is OK with very high resolution monitors.
I will reopen the Issue if necessary.

D.

**Comment by Cipollino** [comment]
All OK now.
