### ISSUE TITLE
Print margins

### ISSUE THREAD

**Issue by Luigi-C** [DarwinNE/FidoCadJ#98]
FidoCadJ version 0.24.6 has a better printing management, with respect to the previous version, expecially the capability to tailor to the page dimensions.
However, final printing shows too wide default margins - 2.55 cm - and impossibile to reduce without having part of the drawing cut.
It seems that this behaviour depends on information provided by Java.
Is there really nothing to do to solve this issue?

**Comment by DarwinNE** [comment]
The default print margins are calculated by taking the maximum printable area declared by the printing drivers handled by Java. In the print preview, FidoCadJ shows in red the region lying outside the declared printable area whereas the margins selected are shown by means of a dashed line. Here is what I get in my case (MacOSX 10.11.2 with a french locale):

![impression](https://cloud.githubusercontent.com/assets/11355790/15221116/61ad28c2-186a-11e6-83ff-621bb9ee058c.png)

It seems that in your case the declared printable area is abnormally small. Maybe a driver issue? Or a Java configuration problem? What is your operating system?

**Comment by Luigi-C** [comment]
Hi Darwin, I tried to set another printer as the default one (PDF Creator virtual printer), but nothing has changed, the printable area remains the same:

![cattura](https://cloud.githubusercontent.com/assets/18629642/15222832/c189c0dc-1871-11e6-9d37-b2083f0f9d69.PNG)

I don't know Java in details and I don't know how to configure it to trim printing margins in FidoCadJ.
My OS is Windows 7 64-bit edition.

**Comment by DarwinNE** [comment]
Hi @Luigi-C,
  it seems that in your case the margins are set to 1 inch (hence 2.55 cm) by the fact that the printable area is declared in this way by your Java system.
For the moment, I do not see any obvious error on the FidoCadJ side, but I will continue to investigate.
Cheers,
D.
